### PR TITLE
Fixed scrollbar color issue

### PR DESCRIPTION
**Pull request by leecheeyong**
I'm not sure if this needs to be added into every theme, I haven't got time to try them out.
But hey, I do love what you've made and I think this is the best working one.

The code I contribute has not yet been minified, maybe you should apply this to all the custom themes then minify them altogether. 

This change fixes the chat scrollbar, which was not modified previously.

Hope you'll review this pull !

### CODE REVIEW

**Comment by oliver408i** [comment]
Hello, can you please just send the bit of code (unminified) that you want to change/add and tell me where it should go? I use a python program to automatically put all the themes together based on a template and then minify and upload to github, so that would be helpful. Also, would you mind sending a screenshot or describing what the issue that you are fixing is? Thanks

**Comment by leecheeyong** [comment]
Before
image

After
image

**Comment by leecheeyong** [comment]
```
javascript: head = document.head;
oldinject = document.getElementById("themecrack");
if (oldinject) {
  oldinject.remove();
}
oldbinject = document.getElementById("basecrack");
if (!oldbinject) {
  baseinjectcss =
    ".theme-dark,.theme-light{--bg-overlay-opacity-2:0.8;--bg-overlay-opacity-3:0.7}.theme-light{--bg-overlay-color:255 255 255;--bg-overlay-color-inverse:0 0 0;--bg-overlay-opacity-1:0.9;--bg-overlay-opacity-4:0.6;--bg-overlay-opacity-5:0.3;--bg-overlay-opacity-6:0.15;--bg-overlay-opacity-hover:0.7;--bg-overlay-opacity-hover-inverse:0.02;--bg-overlay-opacity-active:0.65;--bg-overlay-opacity-active-inverse:0.03;--bg-overlay-opacity-selected:0.6;--bg-overlay-opacity-selected-inverse:0.04;--bg-overlay-opacity-chat:0.9;--bg-overlay-opacity-home:0.7;--bg-overlay-opacity-home-card:0.9;--bg-overlay-opacity-app-frame:var(--bg-overlay-opacity-5)}.theme-dark{--bg-overlay-color:0 0 0;--bg-overlay-color-inverse:255 255 255;--bg-overlay-opacity-1:0.85;--bg-overlay-opacity-4:0.5;--bg-overlay-opacity-5:0.4;--bg-overlay-opacity-6:0.1;--bg-overlay-opacity-hover:0.5;--bg-overlay-opacity-hover-inverse:0.08;--bg-overlay-opacity-active:0.45;--bg-overlay-opacity-active-inverse:0.1;--bg-overlay-opacity-selected:0.4;--bg-overlay-opacity-selected-inverse:0.15;--bg-overlay-opacity-chat:0.8;--bg-overlay-opacity-home:0.85;--bg-overlay-opacity-home-card:0.8;--bg-overlay-opacity-app-frame:var(--bg-overlay-opacity-4)}html{--bg-overlay-1:linear-gradient(rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-1)),rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-1))) fixed 0 0/cover,var(--custom-theme-background) fixed 0 0/cover;--bg-overlay-2:linear-gradient(rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-2)),rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-2))) fixed 0 0/cover,var(--custom-theme-background) fixed 0 0/cover;--bg-overlay-3:linear-gradient(rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-3)),rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-3))) fixed 0 0/cover,var(--custom-theme-background) fixed 0 0/cover;--bg-overlay-4:linear-gradient(rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-4)),rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-4))) fixed 0 0/cover,var(--custom-theme-background) fixed 0 0/cover;--bg-overlay-5:linear-gradient(rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-5)),rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-5))) fixed 0 0/cover,var(--custom-theme-background) fixed 0 0/cover;--bg-overlay-6:linear-gradient(rgb(var(--bg-overlay-color-inverse)/var(--bg-overlay-opacity-6)),rgb(var(--bg-overlay-color-inverse)/var(--bg-overlay-opacity-6))) fixed 0 0/cover,var(--custom-theme-background) fixed 0 0/cover;--bg-overlay-hover:linear-gradient(rgb(var(--bg-overlay-color-inverse)/var(--bg-overlay-opacity-hover-inverse)),rgb(var(--bg-overlay-color-inverse)/var(--bg-overlay-opacity-hover-inverse))) fixed 0 0/cover,linear-gradient(rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-hover)),rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-hover))) fixed 0 0/cover,var(--custom-theme-background) fixed 0 0/cover;--bg-overlay-active:linear-gradient(rgb(var(--bg-overlay-color-inverse)/var(--bg-overlay-opacity-active-inverse)),rgb(var(--bg-overlay-color-inverse)/var(--bg-overlay-opacity-active-inverse))) fixed 0 0/cover,linear-gradient(rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-active)),rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-active))) fixed 0 0/cover,var(--custom-theme-background) fixed 0 0/cover;--bg-overlay-selected:linear-gradient(rgb(var(--bg-overlay-color-inverse)/var(--bg-overlay-opacity-selected-inverse)),rgb(var(--bg-overlay-color-inverse)/var(--bg-overlay-opacity-selected-inverse))) fixed 0 0/cover,linear-gradient(rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-selected)),rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-selected))) fixed 0 0/cover,var(--custom-theme-background) fixed 0 0/cover;--bg-overlay-chat:linear-gradient(rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-chat)),rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-chat))) fixed 0 0/cover,var(--custom-theme-background) fixed 0 0/cover;--bg-overlay-home:linear-gradient(rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-home)),rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-home))) fixed 0 0/cover,var(--custom-theme-background) fixed 0 0/cover;--bg-overlay-home-card:linear-gradient(rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-home-card)),rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-home-card))) fixed 0 0/cover,var(--custom-theme-background) fixed 0 0/cover;--bg-overlay-app-frame:linear-gradient(rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-app-frame)),rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-app-frame))) fixed 0 0/cover,var(--custom-theme-background) fixed 0 0/cover}.form-3gdLxP:before{content:unset!important}.theme-light .modeMuted-2T4MDZ .icon-2W8DHg,.theme-light .modeMuted-2T4MDZ .name-28HaxV{color:var(--primary-330)}.theme-dark .circleIconButton-1VxDrg:not(.selected-2r1Hvo),.theme-dark .expandedFolderBackground-1kSAf6,.theme-dark .wrapper-3kah-n:not(:hover):not(.selected-1Drb7Z) .childWrapper-1j_1ub{background:rgb(var(--bg-overlay-color-inverse)/var(--bg-overlay-opacity-6))}.theme-light .circleIconButton-1VxDrg:not(.selected-2r1Hvo),.theme-light .wrapper-3kah-n:not(:hover):not(.selected-1Drb7Z) .childWrapper-1j_1ub{background:rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-3))}.theme-dark .folder-241Joy{background:var(--bg-overlay-6,var(--background-secondary))}.theme-light .expandedFolderBackground-1kSAf6{background:rgb(var(--bg-overlay-color)/var(--bg-overlay-opacity-5))}.theme-light .folder-241Joy{background:var(--bg-overlay-3,var(--background-secondary))}.scroller-3X7KbA{background:var(--bg-overlay-app-frame,var(--background-tertiary))}.theme-dark .container-1zzFcN{background:var(--bg-overlay-1,var(--background-secondary-alt))}.theme-dark .button-1EGGcP .buttonColor-3bP3fX,.theme-dark .button-1EGGcP.buttonColor-3bP3fX{background:var(--bg-overlay-4,var(--background-primary))}.theme-dark .button-1EGGcP .buttonColor-3bP3fX:hover,.theme-dark .button-1EGGcP.buttonColor-3bP3fX:hover{background:var(--bg-overlay-5,var(--background-secondary))}";
  baseinject = document.createElement("style");
  baseinject.id = "basecrack";
  baseinject.appendChild(document.createTextNode(baseinjectcss));
  head.appendChild(baseinject);
}
themecustomcss =
  "html{--custom-theme-background:" +
  "linear-gradient(128.92deg, var(--bg-gradient-chroma-glow-1) 3.94%, var(--bg-gradient-chroma-glow-2) 26.1%, var(--bg-gradient-chroma-glow-3) 39.82%, var(--bg-gradient-chroma-glow-4) 56.89%, var(--bg-gradient-chroma-glow-5) 76.45%)" +
  "} .auto-2TJ1RH { scrollbar-color: #1a1b1e transparent; }" ;
themeinject = document.createElement("style");
themeinject.id = "themecrack";
themeinject.appendChild(document.createTextNode(themecustomcss));
head.appendChild(themeinject);
```

**Comment by leecheeyong** [comment]
Just a small change

**Comment by oliver408i** [comment]
I see. Can you send only the css that is missing?

**Comment by oliver408i** [comment]
Well, I figured it out, but the code you added doesn't quite work. What browser are you using?

**Comment by leecheeyong** [comment]
I'm using the Mozilla LTS on a macOS

**Comment by leecheeyong** [comment]
> Well, I figured it out, but the code you added doesn't quite work. What browser are you using?

Oh I think its because I've included '```' at the end which causes error

I've edited that, you can that again

**Comment by oliver408i** [comment]
No only took the piece of code you changed, i.e. `.auto-2TJ1RH { scrollbar-color: #1a1b1e transparent; }` It seems that this is not working on Chrome. I tried to apply it to the html root element too. There is a variable in the discord css stylesheet that links to the scrollbar, which seems to function, but by setting it to be transparent, no one can see the scrollbar anymore. I don't think that was how discord wanted it.

**Comment by leecheeyong** [comment]
> No only took the piece of code you changed, i.e. `.auto-2TJ1RH { scrollbar-color: #1a1b1e transparent; }` It seems that this is not working on Chrome. I tried to apply it to the html root element too. There is a variable in the discord css stylesheet that links to the scrollbar, which seems to function, but by setting it to be transparent, no one can see the scrollbar anymore. I don't think that was how discord wanted it.

Oh I think it was a mistake on my side but the transparent scrollbar does match the channels bar, which looks better in my opinion, anyways feel free to close this if you don't feel like implementing.

**Comment by oliver408i** [comment]
Well, thank you for bringing the issue up. I'll see how discord handle the sidebar css and implement that if possible.

**Pull request closed without merging**
